# Generated by Django 3.0.3 on 2020-02-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='repo_name', max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False, help_text='whether the repo is public/private')),
            ],
        ),
        migrations.AddField(
            model_name='githubaccountinfo',
            name='email_subscription',
            field=models.BooleanField(default=True, help_text='toggle this On/Off for email reminders.'),
        ),
        migrations.AddField(
            model_name='githubaccountinfo',
            name='token',
            field=models.CharField(blank=True, help_text="this token will be GitHub user's personal token. Hence user will create the sameat his/her side.", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_time', models.DateTimeField(blank=True, help_text='last time email sent to the user', null=True)),
                ('reminder_type', models.CharField(blank=True, choices=[('CM', 'COMMENTS'), ('RR', 'REQUESTED_REVIEWS')], max_length=2, null=True)),
                ('text_body', models.TextField(blank=True, null=True)),
                ('pr_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_repo', to='reminder.GitRepo')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_reviewer', to='reminder.GitHubAccountInfo')),
            ],
        ),
        migrations.AddField(
            model_name='gitrepo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='git_repo', to='reminder.GitHubAccountInfo'),
        ),
    ]
